"""create_case_history_table

Revision ID: 0d32f3ef9fd5
Revises: 24d240091ec7
Create Date: 2026-09-18 17:19:38.100929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d32f3ef9fd5'
down_revision: Union[str, Sequence[str], None] = '24d240091ec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects import postgresql
    op.create_table('case_history',
    sa.Column('history_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('old_status', postgresql.ENUM('OPEN', 'IN_PROGRESS', 'PENDING', 'RESOLVED', 'CLOSED', name='case_status_enum', create_type=False), nullable=True),
    sa.Column('new_status', postgresql.ENUM('OPEN', 'IN_PROGRESS', 'PENDING', 'RESOLVED', 'CLOSED', name='case_status_enum', create_type=False), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_case_history_case_id'), 'case_history', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_history_history_id'), 'case_history', ['history_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_history_history_id'), table_name='case_history')
    op.drop_index(op.f('ix_case_history_case_id'), table_name='case_history')
    op.drop_table('case_history')
    # ### end Alembic commands ###
